# Generated by Django 5.0.3 on 2024-03-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_listing_bids_bid_bids_listing_bids_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchListing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isWatchlisted', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auctionlisting')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
