# Generated by Django 5.0.3 on 2024-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Collectibles & Art', 'Collectibles & Art'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Books, Music & Media', 'Books, Music & Media')], default=('Electronics', 'Electronics'), max_length=64),
        ),
    ]
