# Generated by Django 5.0.3 on 2024-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_auctionlisting_datlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='datListed',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
