# Generated by Django 5.0.3 on 2024-03-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auctionlisting_datlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='datListed',
        ),
    ]
