# Generated by Django 5.0.3 on 2024-04-11 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_auctionlisting_datlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='datListed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
